config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'athletes#index'

  resources :athletes, only: %i[index show]
  get 'line_chart_data', to: 'athletes#line_chart_data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/athlete.rb
# frozen_string_literal: true

class Athlete < ApplicationRecord
  has_many :challenge_totals, dependent: :destroy

  validates :myzone_usr_guid, uniqueness: true

  CHALLENGE_START = Date.new(2019, 10, 14)

  def self.standings
    includes(:challenge_totals).group(:name).maximum(:points).sort_by { |_name, points| -points }
  end

  def line_chart_data
    challenge_totals.group_by_hour(:created_at).sum(:points).delete_if { |_k, v| v.zero? }
  end
end

app/models/challenge_total.rb
# frozen_string_literal: true

class ChallengeTotal < ApplicationRecord
  belongs_to :athlete, touch: true

  validates :points, numericality: { greater_than: 0 }

  scope :most_recent, -> { order(created_at: :desc).limit(8) }

  scope :most_recent_low_to_high, -> { where(id: most_recent.pluck(:id)).order(:points) }
end

app/models/workout.rb
# frozen_string_literal: true

class Workout < ApplicationRecord
  belongs_to :athlete

  validates :points, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/athletes_controller.rb
# frozen_string_literal: true

class AthletesController < ApplicationController
  def index
    @standings = Athlete.standings
  end

  def line_chart_data
    updated_at_sum = Athlete.pluck(:updated_at).map(&:to_i)
    line_chart_data = Rails.cache.fetch("#{updated_at_sum}/line_chart_data", expires_in: 12.hours) do
      athletes = Athlete.includes(:challenge_totals).order(:id)
      athletes.map { |athlete| { name: athlete.name, data: athlete.line_chart_data } }
    end
    Rails.logger.debug("\n #{line_chart_data.to_json} \n")
    render json: line_chart_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
# frozen_string_literal: true

module AthletesHelper
  def bg_class(idx)
    return 'has-background-danger' if idx == 7
    return 'has-background-grey-lighter' if idx == 3
    return 'has-background-success' if idx < 3

    'has-background-warning' if idx > 3
  end

  def standings_icon(idx)
    return content_tag(:i, nil, class: 'fas fa-user-graduate fa-sm') if idx == 7
    return content_tag(:i, nil, class: 'fas fa-dollar-sign fa-xs') * (3 - idx) if idx < 3

    content_tag(:i, nil, class: 'fas fa-dollar-sign fa-xs has-text-danger') * (idx - 3) if idx > 3
  end

  def points_per_day(points)
    days = (Time.zone.today - Athlete::CHALLENGE_START).to_f
    (points / days).round
  end

  def times_normal(pts)
    (pts / 1300.0).round(2)
  end

  def next_refresh
    # UTC implementation
    # hour = Time.zone.now.hour
    # return '10AM EST' if (3..14).include? hour
    # return '2PM EST' if (15..18).include? hour
    # return '6PM EST' if (19..22).include? hour
    # '10PM EST'

    hour = Time.zone.now.in_time_zone('Eastern Time (US & Canada)').hour
    return '2PM EST' if (10..13).include? hour
    return '6PM EST' if (14..17).include? hour
    return '10PM EST' if (18..21).include? hour

    '10AM EST'
  end
end

app/views/athletes/index.html.haml
%section.hero.is-info.is-bold.is-small
  .hero-body
    .container
      %h1.title Loser Takes the SAT
      %h2.subtitle
        Next Refresh:
        %strong= next_refresh
%nav.level
  .level-item.has-text-centered
    %div
      %p.heading Current Loser
      %p.title.is-size-6-mobile= @standings.last[0]
  .level-item.has-text-centered
    %div
      %p.heading Time Remaining
      %p#countdown.title.is-size-6-mobile
        %i.fas.fa-haykal.fa-spin
  .level-item.has-text-centered
    %div
      %p.heading Cumulative Pts
      %p.title.is-size-6-mobile= number_with_delimiter(@standings.map(&:last).sum)

-# - one_day = Time.zone.today + 1.day
- plus_half_day = Time.zone.now + 12.hours
- end_time = DateTime.new(2019, 11, 14)
- xmax = plus_half_day < end_time ? plus_half_day : end_time

%section#main-content.is-invisible
  .container
    .tile.is-ancestor
      .tile.is-parent.is-6
        .tile.is-child.box
          = line_chart(line_chart_data_path,
                       id: 'line-chart',
                       min: 4000,
                       max: 12000,
                       xmax: xmax.to_s,
                       library: { scales: { yAxes: [{ ticks: { stepSize: 2000 } }] } })
      .tile.is-parent.is-6
        .tile.is-child.box
          %table.table.is-fullwidth.is-hoverable.is-size-7-mobile
            %thead
              %tr
                %th &nbsp
                %th Name
                %th Pts
                %th Pts Back
                %th Avg
                %th x Norm*
            %tbody
              - @standings.each_with_index do |name_pt_arr, idx|
                - pts = name_pt_arr[1]
                %tr{class: "#{bg_class(idx)}"}
                  %td= idx + 1
                  %td{style: {}}
                    %span= name_pt_arr[0]
                    %span= standings_icon(idx)
                  %td= number_with_delimiter(pts)
                  %td= number_with_delimiter(pts - @standings[0][1])
                  -# %td= idx.zero? ? 0 : number_with_delimiter(pts - @standings[idx - 1][1])
                  %td= points_per_day(pts)
                  %td= times_normal(pts)
          %article.message.is-info
            .message-body.is-size-7
              * MyZone recommends 1,300 points/month to reach WHO guidelines for cardiovascular physical activity.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loser Takes the SAT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>